### ISSUE TITLE
Copy & pasting verification code as part of the signup process

### ISSUE THREAD

**Issue by Capsup** [WemXPro/tracker#113]
### Resource

WemX Pro

### Describe the solution you'd like

Currently, it is not possible to copy paste the verification code into the field because each of them are separate text boxes and the clipboard contents doesn't "spill over" into the remaining fields.

It would be nice if it was possible to select the verification code from e-mail, press ctrl + c, tap onto the registration page, select the text field for the first number, press ctrl + v and have it fill out all of them rather than just the first number.

**Comment by Mubeen142** [comment]
Hi, a fix for a similar issue has been made for issue #117

**Comment by GIGABAIT93** [comment]
This will be added in the next update
