### ISSUE TITLE
Ticket System

### ISSUE THREAD

**Issue by Shockingg** [WemXPro/tracker#115]
### Resource

WemX Pro

### Describe the solution you'd like

Just like old billing, would love to see a ticket system implemented to provide support directly through the website to avoid having to direct users to a discord server or to contact via email. I'm sure I'm not the only one that would love to see this added. If it does get added it would be great to make use of the notifications menu to show users that they've received a new message.

**Comment by Sam-fr** [comment]
I need this feature too. Is there a release date for this feature?
