### ISSUE TITLE
Auto Discord Role

### ISSUE THREAD

**Issue by DartNodes** [WemXPro/tracker#121]
### Resource

WemX Pro

### Describe the solution you'd like

How about implementing an automated system that assigns the "Customer" role on our Discord server to users who have successfully linked their Discord accounts to Wemx? This feature would offer numerous advantages and elevate the overall user experience.

By integrating this feature, we can seamlessly recognize and reward our customers who have connected their Discord accounts with Wemx. Once the linkage is established, these individuals will automatically receive the exclusive "Customer" role on our Discord server, gaining access to dedicated channels, special privileges, and personalized benefits.

This suggested enhancement aims to prioritize our customers and demonstrate our appreciation for their loyalty. By automating the role assignment process, we can eliminate the need for manual verification and streamline the experience for our users. It not only saves time and effort but also ensures that deserving customers receive their well-deserved recognition promptly.

### Additional context

I used chatgpt for this text eh

**Comment by GIGABAIT93** [comment]
This is only possible if you have a Discord bot for this. I don't think that it will be implemented in wemx directly because we don't have a Discord bot planned. If you need it, it can be implemented using wemx modules

**Comment by Partymann2000** [comment]
> This is only possible if you have a Discord bot for this. I don't think that it will be implemented in wemx directly because we don't have a Discord bot planned. If you need it, it can be implemented using wemx modules

You can use the discord api you dont need a bot
