### ISSUE TITLE
duration edit plans

### ISSUE THREAD

**Issue by NolayDscd** [WemXPro/tracker#135]
### Resource

WemX Pro

### Describe the solution you'd like

Add the ability to edit the duration of the plan when it's already created, instead of deleting and recreating it.

**Comment by PadowYT2** [comment]
> ### Resource
> WemX Pro
> 
> ### Describe the solution you'd like
> Add the ability to edit the duration of the plan when it's already created, instead of deleting and recreating it.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

Well then what would happen to already existing orders?

**Comment by NolayDscd** [comment]
They will be updated upon the due date.
