### ISSUE TITLE
Tax and VAT for Orders

### ISSUE THREAD

**Issue by SamuelBrownSE** [WemXPro/tracker#151]
### Resource

WemX Pro

### Describe the solution you'd like

Have the ability to Add TAX or VAT to an order.

its pretty straightforward... depending what country you're in you apply the right tax.

**Comment by PadowYT2** [comment]
Shouldn't the payment gateways include it, not WemX Pro?

**Comment by SamuelBrownSE** [comment]
The payment gateways get the information from the wemx though?

**Comment by VanillaChan6571** [comment]
> The payment gateways get the information from the wemx though?

PayPal doesn't and will use the buyer's billing information that's saved if the user logs in.

**Comment by SamuelBrownSE** [comment]
so PayPal just makes the amount up do they? xD that makes zero sense, the billing panel provides the amount to the gateway, example, if I select a plan thats £4, the gateway gets that information, that someone has selected the amount of £4 and charges them that much, I want it so its £4 ex VAT on the front page but then adds the VAT on the checkout.

**Comment by Mubeen142** [comment]
This was added in a previous update. Closing the issue for that reason
