### ISSUE TITLE
Allocations to certain games

### ISSUE THREAD

**Issue by SamuelBrownSE** [WemXPro/tracker#157]
### Resource

WemX Pro

### Describe the solution you'd like

Anyway of an addon that allows you control over what ports get assigned to a specific game? Example - if I wanted Minecraft servers to give a certain port say varying from 25535 – 25540 rather than it being random? as I sell csgo server with ports from 27015 - 27020 but these are getting assigned automatically to the Minecraft servers.

### Describe alternatives you've considered

I could delete the servers and reinstate them, but then what's the point in the wemx.

**Comment by GIGABAIT93** [comment]
We added the ability to specify the port range for the node, this will be available in the new update. There are currently no plans to specify a range for the Nets

**Comment by Gresakm** [comment]
Automatic port creation in a certain range for each egg separately would be good because OVH supports L7 anti DDoS filtering for different games but you have to set specific ports and specific games to ports in advance.

**Comment by Mubeen142** [comment]
This was already added in a previous update
