### ISSUE TITLE
Steam Login in

### ISSUE THREAD

**Issue by Davidbp99** [WemXPro/tracker#16]
### Resource

Socialite

### Is your feature request related to a problem? Please describe

Steam Login is something that is very normal if you run a server that is from steam. Like gmod, SCP, arma 3 and more.

### Describe the solution you'd like

Add steam login to the panel

**Comment by PadowYT2** [comment]
No idea if this possible due to limitations, but if @Mubeen142 cannot make it, this will be closed

**Comment by PadowYT2** [comment]
Kamino closed and cloned this issue to [VertisanPRO/tracker](https://github.com/VertisanPRO/tracker/issues/1)
