### ISSUE TITLE
Adding a tick when registering the acceptance of TOS

### ISSUE THREAD

**Issue by Mr-sl1d3r** [WemXPro/tracker#165]
### Resource

WemX Pro

### Describe the solution you'd like

as per title it would be very useful to have the function that when a user registers he/she has to accept the terms of service

**Comment by Mubeen142** [comment]
Thanks, this was added

**Comment by Mubeen142** [comment]
To add the checkbox, you must create a custom page in the admin area with path `terms-and-conditions`

WemX will recognize your application has terms and ask the user to accept them at checkout and registration
