### ISSUE TITLE
Translation errors and revision

### ISSUE THREAD

**Issue by Partymann2000** [WemXPro/tracker#167]
### Resource

WemX Pro

### Describe the issue

I have tried to translate everything into German but I find that very confusing arranged and it is also missing a few keys and I think you should revise it villeicht everything still a bit more kategorisiereen eg extra translation f+r email because a hello in the client.php I know eg not that should belong to the emails

Here are a few errors that I have noticed
1. What does this have to do with client.php
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/84a11ded-bd05-4a6b-ab48-a6878cb776bf)

2. that is completely missing
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/4712020c-d49b-49ab-a1da-f6f22cf24240)

3. or what is that I have not found anywhere
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/9ce380d5-6da3-4b55-8c54-56f37f37d5cf)

4. this should be renamed to email_address or email_greeting or best make an extra file for the email things
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/372fc587-22fb-4cbf-a16e-1bdc93247d73)

5. you should be able to translate :period because it says english only 
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/eed39cda-5d79-4b42-b77e-05082204ea08)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.3.0

**Comment by GIGABAIT93** [comment]
Are you still having the problem with the new version?

**Comment by GIGABAIT93** [comment]
was fixed in past versions
