### ISSUE TITLE
Sync Sign ins to same account

### ISSUE THREAD

**Issue by Davidbp99** [WemXPro/tracker#17]
### Resource

Socialite

### Is your feature request related to a problem? Please describe

Be enabled to add other sign in on the account at https://your-domain.com/account (or if you use ip)

### Describe the solution you'd like

So lets say I create the account with discord. Then on /account I can add my github to be enabled to sign into the same account.
Should be enabled to unlink as well. But must have one connected to the account at all time. Unless Admin overwrites it with an email.

**Comment by PadowYT2** [comment]
Kamino closed and cloned this issue to [VertisanPRO/tracker](https://github.com/VertisanPRO/tracker/issues/2)
