### ISSUE TITLE
[Feature Request] Discord Notifications for payments/orders

### ISSUE THREAD

**Issue by MxLNinjaz** [WemXPro/tracker#172]
### Resource

WemX Pro

### Describe the solution you'd like

What I would like is a section on the admin panel where you can setup a webhook link to your discord channel that will send notifications for the following:

- Payment Received
- New Orders
- Order Cancelled
- Order Terminated

### Describe alternatives you've considered

The alternative would be able to set email address which receive emails for the notifications mentioned above.

**Comment by GIGABAIT93** [comment]
Already implemented and can be configured in the webhooks section of each package
