### ISSUE TITLE
Portal page alignment

### ISSUE THREAD

**Issue by Shockingg** [WemXPro/tracker#175]
### Resource

WemX Pro

### Describe the solution you'd like

Would be nice to have most of the elements on the portal / home page centered, especially on mobile, things just a look a little strange on mobile. Just looks a little strange when you have almost everything else centered except for these things, examples are below. 

<img width="1305" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/137300798/f388d1b3-85c8-4f5e-bc9d-1c335417b6f4">
<img width="1553" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/137300798/f9ac2176-cbf6-4729-a7f7-b5e8f2a4d73d">

**Comment by VanillaChan6571** [comment]
Since this is a portal template, you can modify this. This may not be added or changed due to it being just a template.
