### ISSUE TITLE
Important information displayed in footer

### ISSUE THREAD

**Issue by Shockingg** [WemXPro/tracker#176]
### Resource

WemX Pro

### Describe the solution you'd like

Would be great to have important information such as company name, company address etc displayed in the footer under the website name. As right now it's just blank.

<img width="1570" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/137300798/626f8c54-aabd-45ac-b758-158ab0bf9c24">

**Comment by Mubeen142** [comment]
You can create custom pages and select the footer as the location. You can also make these pages redirect to external/custom links
