### ISSUE TITLE
Discord oauth doesn’t show on login screen. 

### ISSUE THREAD

**Issue by starrider346** [WemXPro/tracker#207]
### Product

WemX Pro

### Describe the issue

I have Discord oauth setup and it works when linking in account settings. 

However when you go to the login screen, the button to login with Discord is nowhere. 

### Pterodactyl Panel Version

1.5.0

### Product Version

-

### To Reproduce

1. Setup Discord oauth
2. Go to the login page

### Expected Behaviour

These is a button that allows you to login with Discord

### Screenshots

![IMG_3390](https://github.com/VertisanPRO/pterodactyl/assets/58882729/5e704bff-0596-40a6-8ae5-39b6cabcf1e5)
![IMG_3389](https://github.com/VertisanPRO/pterodactyl/assets/58882729/9a370c30-6017-4b9d-b77a-8136f5ab6316)

**Comment by VanillaChan6571** [comment]
Not a bug, It does nothing at this time.

**Comment by Mubeen142** [comment]
Hi,

I have removed the "Allow users to login" button to avoid confusion.
