### ISSUE TITLE
Analytics/Tracking for ADs

### ISSUE THREAD

**Issue by uplandstatue** [WemXPro/tracker#210]
### Product

WemX Pro

### Describe the solution you'd like

To advertise and grow our services many of these things require some form of either page modification or the capability to simply add the tracking ID for it to connect to your add account. Using Google Ads requires this. Not sure if it is needed enough or this is just us.

### Describe alternatives you've considered

None

**Comment by VanillaChan6571** [comment]
No

**Comment by SiFuMax09** [comment]
Why???
Ads are discussing

VanillaChan Good opinion 

Also this need to be implemented in the theme not in the WemX Core

**Comment by Mubeen142** [comment]
Thank you for your suggestion, Google analytics was added and can be setup in the general settings area
