### ISSUE TITLE
Proxmox support

### ISSUE THREAD

**Issue by SprayerGaming** [WemXPro/tracker#217]
### Product

WemX Pro

### Describe the solution you'd like

Add the ability to support Proxmox Virtual Envirovement so ppl can create / order vps packages.
This should include everything as possible.
Some samples: 

- cloning an existing VM template + applying the configuration for the new VM (as the config is served trough Wemx page) all this trough proxnox API
-buttons for VM management start shutdown hard stop 
- a reinstall button  - cloning down other VM template with other OS on it 
- console button to open up VNC or exterm.js console 
- Rescue mode - VM should boot into a live ISO such as Finnix Rescue CD
- Ability to make not only QEMU but LXC instances too with every single templates available which can be selected by the user
- Set of the password of the VM trough cloud-init which is in Proxmox 
- Set an IPv4 adress automatically trough some DHCP server or so
- Set a custom hostname - proxmox API call as everything else
 
And much more ....

**Comment by VanillaChan6571** [comment]
1. Isn’t proxmox a paid/license software?
2. Most likely be a module feature

**Comment by SprayerGaming** [comment]
1. Proxmox is an open source, free to use software for everyone but in addition there is an existing Enterprise version which is for sure paid, but they don't rlly care about if you are using it for enterprise or hobby uk. 

2. It is yes, just like Pterodactyl is.

**Comment by OllyInBlue** [comment]
Will this be included eventually?

**Comment by Mubeen142** [comment]
Hi @SprayerGaming 

I am interesting adding support for Proxmox. Do you have this panel installed? If so please contact me on Discord so that we can do some testing

**Comment by EWANZO101** [comment]
> Hi @SprayerGaming
> 
> I am interesting adding support for Proxmox. Do you have this panel installed? If so please contact me on Discord so that we can do some testing

i woud be happy to let u test it on my Proxmox as well

**Comment by EWANZO101** [comment]
I would be happy to also allow u to test it on my Proxmox

**Comment by Mubeen142** [comment]
@SprayerGaming 

Currently I am working on adding Proxmox,, You can track progress here: https://github.com/WemXPro/service-proxmox

You mentioned that a user should be able to manage their server from WemX, but why not create an account for the user and email them the details so that they can manage their server directly on Proxmox panel?
