### ISSUE TITLE
Edit Features in the Package Feature tab

### ISSUE THREAD

**Issue by DenDanskeMine** [WemXPro/tracker#224]
### Product

WemX Pro

### Describe the solution you'd like

Right now you cannot edit the list, only delete or change the lising order.

Add a button `Edit` to allow the user to ediit the feature esaly without deleting it.

Its a bit tedious to delete and remake features, when you clone packages.

I hope my idea make sense :)

![Opera Snapshot_2023-10-02_133245_danbyte net](https://github.com/VertisanPRO/pterodactyl/assets/114334271/3ca659c1-50bc-47d3-8615-b2100468e709)

### Describe alternatives you've considered

no maybe edit it in phpmyadmin? but at that point, its just faster to delete it, and make a new one.

**Comment by VanillaChan6571** [comment]
Yes right now the way to edit features is to use PhpMyAdmin

**Comment by VanillaChan6571** [comment]
Most likely. @Mubeen142 would only know.

**Comment by Mubeen142** [comment]
Hi

Thanks for the suggesting. I will try including it next major release

**Comment by GIGABAIT93** [comment]
Will be added in the next update
