### ISSUE TITLE
Small UI/UX Anomalies

### ISSUE THREAD

**Issue by Stan805** [WemXPro/tracker#226]
### Product

Unix

### Describe the issue

There are some small scattered errors throughout certain sections that I would like to point out. I have attached screenshots with markup showing exact issues.

### Pterodactyl Panel Version

1.11.3

### Product Version

4.1.5

### To Reproduce

1. Switch theme to light mode, and the icon inside the light/dark mode toggle will disappear; this is universal.
2. Majority of glitches are seen in the schedules and backups sections in game servers, as shown in all uploaded screenshots. There is one exception, and it is prevalent in the network section of any game server.

### Expected Behaviour

All UI elements should display correctly without any glitches, overlapping, or invisibility issues. Icons, buttons, and text should be visible and correctly aligned, irrespective of the mode (light/dark).

### Screenshots

![Screenshot 2023-10-08 155032](https://github.com/VertisanPRO/pterodactyl/assets/144626532/3ba08b4b-c9a1-4bd0-9da0-c5f618e28740)
![Screenshot 2023-10-08 155117](https://github.com/VertisanPRO/pterodactyl/assets/144626532/08f36f92-4e13-484d-ac2c-c97702339a3a)
![Screenshot 2023-10-08 155703](https://github.com/VertisanPRO/pterodactyl/assets/144626532/dd4d7e91-a79d-459d-b687-d70f2a34cef1)
![Screenshot 2023-10-08 160014](https://github.com/VertisanPRO/pterodactyl/assets/144626532/25bfae5a-3415-47ff-b8bc-db22a00eccba)
![Screenshot 2023-10-08 160353](https://github.com/VertisanPRO/pterodactyl/assets/144626532/77627e65-ce3f-4d30-b0f6-99de6ae03a9a)
![Screenshot 2023-10-08 154035](https://github.com/VertisanPRO/pterodactyl/assets/144626532/8613f67c-befb-45c9-8559-afd3f6f00042)
![Screenshot 2023-10-08 154359](https://github.com/VertisanPRO/pterodactyl/assets/144626532/47bdf4bc-a9aa-49e4-bce6-5b794a975cb0)
![Screenshot 2023-10-08 154828](https://github.com/VertisanPRO/pterodactyl/assets/144626532/77fab54c-1e2d-4a36-b1d0-c09ba5e8d23f)

### Additional Information

Red Markup = Error.
Green Markup = Works in other visual mode.

**Comment by PadowYT2** [comment]
Thank you for reporting the problems, althought what do you mean in the yellow boxes?
![https://cdn.padow.ru/NG4V0](https://cdn.padow.ru/NG4V0)
![https://cdn.padow.ru/APYMl](https://cdn.padow.ru/APYMl)
![https://cdn.padow.ru/MeYQQ](https://cdn.padow.ru/MeYQQ)

**Comment by Stan805** [comment]
Hi Padow, so in the first 2 images, its very difficult to see, but the boarded for the boxes. I have attached a closeup image. For the third box, I just labeled that that's the network tab in blue, and added a note saying that the issue occurs in both dark and light mode.
![image](https://github.com/VertisanPRO/pterodactyl/assets/144626532/3508ca79-f01c-442f-b15f-3318c19cc672)

**Comment by PadowYT2** [comment]
Kamino closed and cloned this issue to [VertisanPRO/tracker](https://github.com/VertisanPRO/tracker/issues/5)
