### ISSUE TITLE
Income Forecast Report

### ISSUE THREAD

**Issue by simplylate** [WemXPro/tracker#230]
### Product

WemX Pro

### Describe the solution you'd like

The ability to run a report to see your earnings forecast, if all subscriptions are renewed:

An example of this is:
January: Monthly - £10, Quarterly: £30, Annual: £100 - Total: £140
Feburary: Monthly - £10, Quarterly: £15, Annual: £0- Total: £140

Total Forecasted: £___

This feature is in WHMCS and is a dealbreaker for us as we need to be able to have a clear way to see what money is coming in so we can work out Profit/Loss on demand without needing to go through every transaction.

### Additional context

We currently run WHMCS and considering moving to WemX

**Comment by Mubeen142** [comment]
This is something I have been thinking about adding in a new "Insights" page where you can see revenue coming in and other data.


The projected revenue will show each month, jan to dec with the estimated earnings from concurrent subscribers as well as a option to see what this projected revenue would look like with i.e a 10% growth each month.

The other thing I plan on adding to this page is the ability to add projected (Variable and fixed) costs

If you have more suggestions feel free to throw them here

**Comment by simplylate** [comment]
100% we would switch over to WemX if that got implemented.

**Comment by VanillaChan6571** [comment]
This was added around wemx 1.7.2 or so.

If your not suggesting whats already in the admin panel, let them know.
