### ISSUE TITLE
Sort & Filter Users

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#237]
### Product

WemX Pro

### Describe the solution you'd like

Sort and Filter Users by as example State of the Account and so on

**Comment by Crimson7806** [comment]
maybe add custom tags/labels to users? such as Friends, partners, Admins, custom, etc

**Comment by Niclas-M1** [comment]
> maybe add custom tags/labels to users? such as Friends, partners, Admins, custom, etc

You can use Roles I would say

**Comment by GIGABAIT93** [comment]
Will be added in the next update
