### ISSUE TITLE
Edit the Info for Embeds in Admin Interface

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#240]
### Product

WemX Pro

### Describe the solution you'd like

Make it possible to change the Info shown as example, if you send the link in Discord, the embed which is shown there should please be editable using the Admin Interface and not somewhere in the code (what will be erased everytime we update the System)

**Comment by VanillaChan6571** [comment]
Client Theme, stop using the default tailwind folder.

**Comment by Partymann2000** [comment]
@Niclas-M1 Niclas-M1
Paste this theme to resources\themes\portal and activate the theme and edit the settings
[xenority.zip](https://github.com/WemXPro/tracker/files/13400821/xenority.zip)

**Comment by Mubeen142** [comment]
Thanks for suggesting this. It's been added in the next update in

Admin -> Configuration -> SEO

You can customize descriptions, title and the image
