### ISSUE TITLE
Persistent Article Formatting and Submission Problem (Articles)

### ISSUE THREAD

**Issue by LuluKingGithub** [WemXPro/tracker#244]
### Product

WemX Pro

### Describe the issue

Whenever I attempt to submit an article, it consistently produces an abnormal output. Despite my attempts to resolve the problem by deleting articles, refreshing the page, and clearing the cache, the issue persists. Furthermore, there is an additional problem where, upon clicking the submit button (when the article is properly labeled and set to "published"), it fails to return to the list of articles and remains unchanged.

### Pterodactyl Panel Version

0.0.0.0

### Product Version

Latest

### To Reproduce

    Create or edit an article.
    Attempt to submit the article.
    Observe the unusual formatting or appearance.
    Try deleting the article.
    Refresh the page.
    Clear the cache in an attempt to resolve the issue.
    Set the article as "published."
    Click the submit button.

### Expected Behaviour

The article should be submitted without any unusual formatting issues. Deleting, refreshing, or clearing the cache should not be necessary to maintain the proper appearance of the article. When the "submit" button is clicked, the article should return to the list of articles as expected. First article i did was normal and had no problem.

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/85747949/92eac690-78c2-480b-958c-4a37d54d0d25)
![image](https://github.com/VertisanPRO/pterodactyl/assets/85747949/a1f1c970-9547-42b2-a488-e272b465951d)
![image](https://github.com/VertisanPRO/pterodactyl/assets/85747949/1af4356a-48fa-4a65-b11a-fa7659e62263)
![image](https://github.com/VertisanPRO/pterodactyl/assets/85747949/4b382e04-a1f9-45da-98d9-640b4d6f9ba5)

### Additional Information

The submitted article consistently appears with formatting issues. Attempts to rectify the problem through deletion, refreshing, or cache clearing have been ineffective. Additionally, clicking the submit button sometimes fails to return the user to the list of articles.

**Comment by LuluKingGithub** [comment]
In addition to the previously mentioned issues, there is another significant concern. When attempting to disable the 'show author' option, it appears that the feature does not effectively hide the author's information as intended. As shown below; 
![277240094-92eac690-78c2-480b-958c-4a37d54d0d25](https://github.com/VertisanPRO/pterodactyl/assets/85747949/e3692562-4c42-4c5f-ac3e-cf0f4d2d2cd8)

**Comment by Mubeen142** [comment]
Hi @LuluKingGithub 

Thank you for reporting this issue. In the next update, I have added a brand new "short description" field in the articles edit page where you can define the a short description.

This should also fixes the issue caused with formatting
