### ISSUE TITLE
Verification Emails Not sent when Account Activation is set to Email verification and admin approval

### ISSUE THREAD

**Issue by ShadowPro1** [WemXPro/tracker#247]
### Product

WemX Pro

### Describe the issue

When in registration settings if you set Account Activation to Email verification and Admin approval then it won't send the verification email.

### Pterodactyl Panel Version

1.11.5

### Product Version

v1.7.2 

### To Reproduce

Pretty eazy to reproduce just go to admin/settings/registrations  then at Account Activation set Email verification and Admin approval then see how it won't even send the verification email and it just buypasses the email verification.

### Expected Behaviour

Should work yk.

**Comment by VanillaChan6571** [comment]
Email verification and Admin Approval, It seems in the code it more of "Admin Approval Only". I don't see it sending a verification as the account is created but is awaiting approval for an admin. So maybe this is just "Admin Approval Only"

**Comment by Mubeen142** [comment]
Hi there,

The setting is worded incorrectly, I have changed it to "Manual Admin Approval"

It wouldn't make much sense to require email verification after an admin has approved a user
