### ISSUE TITLE
Balance gateway name is not corect 

### ISSUE THREAD

**Issue by SiFuMax09** [WemXPro/tracker#258]
### Product

WemX Pro

### Describe the issue

The name what is set in the gateways tab in the admin panelis not dispayed to the user corectly

### Product Version

WemX 1.8.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

Go to admin -> gateways -> Create Gateway -> Balance
That give it a name that is not ``pay with balance`` -> Create
Try to buy something use ``pay with balance`` gateway

### Expected Behaviour

The name what is given in the gateway creation is not the same what is dispayed to the users

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/131544883/b9c0a91b-7453-49ff-bbc6-a1a644cf408f)
![image](https://github.com/VertisanPRO/pterodactyl/assets/131544883/5d3a7ff2-b3d3-4e61-bba8-fd06f09074d4)
![image](https://github.com/VertisanPRO/pterodactyl/assets/131544883/99215fd9-af09-4966-9710-509a00416331)

**Comment by Mubeen142** [comment]
Thanks for reporting this, however this was done purposely as the balance gateway has a custom name. If you wish to modify it, i believe you can do so in the language files
