### ISSUE TITLE
No Gateway set

### ISSUE THREAD

**Issue by SiFuMax09** [WemXPro/tracker#261]
### Product

WemX Pro

### Describe the issue

A Gateway problem

### Product Version

WemX 1.8.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

Admin -> Subscription -> Create Payment -> Set Status to Refunded or Paid -> Create it -> Error 500 -> Trying to access array offset on value of type null, no gateway was  set

### Expected Behaviour

The payment will be created and a gateway will be set.

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/131544883/098b80e5-c71f-4c94-a6c1-b9a3b36d0e86)
![image](https://github.com/VertisanPRO/pterodactyl/assets/131544883/9a9ebfda-f414-4396-9a5f-349971f96002)

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
