### ISSUE TITLE
Sign out bug

### ISSUE THREAD

**Issue by llyrdavies** [WemXPro/tracker#263]
### Product

WemX Pro

### Describe the issue

When the website in **maintenance mode** the sign out button does nothing.

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

1. Enable maintenance mode
2. Try to sign out via client account

**Comment by Mubeen142** [comment]
Thanks for reporting this issue, it's been fixed for next update.
