### ISSUE TITLE
Username Checkout Variable

### ISSUE THREAD

**Issue by llyrdavies** [WemXPro/tracker#266]
### Product

WemX

### Describe the issue

The "USERNAME" checkout variable still does not work, it was supposed to be fixed a long time ago now but the issue persists. Other variables like "RANDOM_TEXT", "AUTO_PORT" etc work fine however. 

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.5

### Expected Behaviour

replace USERNAME with the users username

**Comment by VanillaChan6571** [comment]
How are you attempting to use USERNAME? example, "USERNAME - Game Server" will not work because GIGABAIT refuses to support or use proper placeholders for certain variables.

**Comment by llyrdavies** [comment]
Yes im using it via "USERNAME - Game Server", but why would he refuse to support that? That just makes no sense

**Comment by GIGABAIT93** [comment]
i.e. do you need to make the placeholders work with other text?

**Comment by VanillaChan6571** [comment]
> i.e. do you need to make the placeholders work with other text?

Correct, Like before ""USERNAME" - Game Server" or :USERNAME: - Game Server

**Comment by GIGABAIT93** [comment]
will be added in future versions
