### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by llyrdavies** [WemXPro/tracker#273]
### Product

WemX

### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/146123002/58783bd2-f6b0-4b55-a065-40d5d7ca5acf)

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.5

**Comment by Mubeen142** [comment]
This issue was fixed in the newer update.

To remove the invalid language, delete folder /var/www/wemx/resources/lang/br
