### ISSUE TITLE
Two buttons have the same text

### ISSUE THREAD

**Issue by Partymann2000** [WemXPro/tracker#275]
### Product

WemX

### Describe the issue

The button with which you can cancel a plan is called the key cancel but the same is also the case with the delete account button there is the same as with the cancel/abort but that makes no sense in German, for example, because the delete account must say "abbrechen" and the cancel/abort plan "Kündigen" because cancel is not correct there
Plans section
![image](https://github.com/WemXPro/tracker/assets/53320411/f13987a3-d67a-4282-825a-a5a2a5ca453e)
Delete accoutn section
![image](https://github.com/WemXPro/tracker/assets/53320411/f4e76605-a644-4734-aa9e-25bdb458830c)
and instead of making the colour green you should also make it red

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.3

**Comment by GIGABAIT93** [comment]
This is a translation problem
