### ISSUE TITLE
Sign up-

### ISSUE THREAD

**Issue by sambrown03** [WemXPro/tracker#278]
### Product

WemX

### Describe the issue

Had a customer have an issue where they went to sign up and input the wrong email and clicked Verify email, once on this page they noticed the email was wrong and tried to click back a page, using the navigation, even if i reload the billing page I cannot get out of the verifying email address page. Unless I verify the email manually.
![image](https://github.com/WemXPro/tracker/assets/147182254/7a841594-18fd-41a9-9fda-b61c54c6ff14)

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

Created a account and once at the verify account stage try to go back or get off the page.

### Expected Behaviour

To go back to the sign up page

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/147182254/8c8fa5dd-edaa-4d94-9e04-08efebb4e3f6)

### Additional Information

Mod edit: there should be a text field, asking if the user inputted a wrong email, if they did, we will clear the email history and whatever was linked to the wrong email, then redirect them back to the "Personal Info" page, so they will be able to edit it

**Comment by PadowYT2** [comment]
I don't really see a fix for this, the user should logout, but then it is their fault that they inputted the wrong email

**Comment by SiFuMax09** [comment]
But its not possible to logout. Only of you clear the cookies.

**Comment by PadowYT2** [comment]
> But its not possible to logout. Only of you clear the cookies.

So, what do you see as a fix? We cannot allow people to go back a page, as it will just have **a lot** of upcoming problems

**Comment by SiFuMax09** [comment]
Create a button that the user can say his email is not corect and set the correct email. Also you can add A button to logout

**Comment by sambrown03** [comment]
Yeah allow for the email to be changed, as its a human error, you can't just say, well get people to not make a mistake, thats not how life works.

**Comment by GIGABAIT93** [comment]
In the next update, a button will be added that will allow you to cancel registration and register again
