### ISSUE TITLE
Client to Payments Cover Fees

### ISSUE THREAD

**Issue by simplylate** [WemXPro/tracker#279]
### Product

WemX

### Describe the solution you'd like

The ability to put all payment processing fees onto the client & the possibility to add on fees per payment gateways (ie: An extra pound or two) 

### Describe alternatives you've considered

I've seen WHMCS addons doing this: 
https://marketplace.whmcs.com/product/2966-services-fee

**Comment by VanillaChan6571** [comment]
Not possible for some/most gateways? gigabait would need to see if possible with some gateways?

**Comment by VanillaChan6571** [comment]
Some Gateways like Tebex / PayPal Business has an option to let the client cover the fees.

And Packages already have a "setup" fee added in Wemx 1.6.0 or so.
