### ISSUE TITLE
Administration Toggle Mode button does not activate and causes 500 error.

### ISSUE THREAD

**Issue by JasmeowTheCat** [WemXPro/tracker#280]
### Product

WemX

### Describe the issue

Trace: https://jasmeow.pics/HuUdl3.txt

### Product Version

Unable to locate - It is the latest. Nowhere on the application states the actual version. Perhaps include that in documentation?

### Pterodactyl Panel Version

1.11.5

### To Reproduce

1. Go to administration panel.
2. Click toggle mode next to the language in the top right. (The moon logo)
3. 500 error as stated.

### Expected Behaviour

N/A - Not really sure. Either switch between dark and light mode OR switch layouts?

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/81937080/d10e1c07-7a98-467f-81a8-c6382e9f896a)

### Additional Information

Not applicable.

**Comment by PadowYT2** [comment]
Known issue, the fix is in the pins of the support channel. In order to get to it, please go to https://wemx.net/dashboard and claim your support role
