### ISSUE TITLE
Support for IND currency in product 

### ISSUE THREAD

**Issue by Ariz-z** [WemXPro/tracker#281]
### Product

WemX

### Describe the solution you'd like

I am from india and i was trying to add stripe payment gateway and trying to test the payment system. But stripe don't allow us to pay in USD currency. 

![image](https://github.com/WemXPro/tracker/assets/43195493/3239e641-4a87-4d0d-af5b-50197991975e)

**Comment by PadowYT2** [comment]
You can add it yourself in `config/utils.php`
