### ISSUE TITLE
The new Member Feature and Cancelation of a Gameserver on Ptero

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#282]
### Product

WemX

### Describe the solution you'd like

Question about the new "Member" Feature:
> If I share a specific Server for a other User and he accepts, he can login into my whole Account in ptero, so he can also see all my. other Servers, which I maybe didn't want to share with him.
> -> would it be more usefull, if you would just add the other User as a Subuser in ptero to the Server and keep the SSO to his own Account?

And When someone cancels there Order in Ptero, would it be smarter, to stupend the Server, while waiting before deletion, if heute wants to recover it

**Comment by PadowYT2** [comment]
This isn't a Q&A repository

**Comment by Niclas-M1** [comment]
They are Ideas, not Questions.
