### ISSUE TITLE
[Language] Support Polish Language and currency

### ISSUE THREAD

**Issue by maxwhitepl** [WemXPro/tracker#286]
### Product

WemX

### Describe the solution you'd like

We want Poland to support this project as well, so we have created a language ready to be introduced and a Polish currency that will help many people sell on our market

[pl.zip](https://github.com/WemXPro/tracker/files/13602647/pl.zip)

### Describe alternatives you've considered

- Possibility of Polish language for the panel (we have a ready file of the language)
- Introduction of Polish Zloty as the currency to pay

### Additional context

If you have any questions, I'm always happy to help with development

**Comment by PadowYT2** [comment]
You can make a Pull Request to WemXPro/languages, thank you
