### ISSUE TITLE
tax

### ISSUE THREAD

**Issue by Turkidev** [WemXPro/tracker#288]
### Product

WemX

### Describe the solution you'd like

saudi arabia tax

### Describe alternatives you've considered

its 15%

**Comment by Turkidev** [comment]
"SA" => [
            "country" => "Saudi Arabia",
            "vat_name" => "VAT",
            "vat_abbr" => "VAT",
            "standard_rate" => 15,
            "reduced_rate" => false,
            "reduced_rate_alt" => false,
            "super_reduced_rate" => false,
            "parking_rate" => false,
        ],

**Comment by Mubeen142** [comment]
Hi,

We have added Saudi Arabia tax in the next update :)
