### ISSUE TITLE
Pterodactyl - members page -> Add Users as Subusers, not like it is now

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#293]
### Product

WemX

### Describe the solution you'd like

When I add a Person to my Pterodactyl Gameserver on WemX, he ha sAccess to my whole Account on Petero.
> it would be better, if the added user just get's added as a Subuser in Ptero

**Comment by Mubeen142** [comment]
Hi @Niclas-M1 

I believe the user can enable an option to not allow users to login to their account. Anyway, this is not something that will be implemented as users can already invite subusers from pterodactyl
