### ISSUE TITLE
Add 2FA support for Security Keys

### ISSUE THREAD

**Issue by TheBestPenguinYT** [WemXPro/tracker#295]
### Product

WemX

### Describe the solution you'd like

Add a section to add Security Keys as a 2FA option.

**Comment by Mubeen142** [comment]
Hi @TheBestPenguinYT 

I made some changes. When you hover over the QR code, it shows the secret key for the 2FA. The user can manually enter that into their favorite authenticator app

**Comment by TheBestPenguinYT** [comment]
You could use the Security Key app, but it would be nice to use the physical key on the website rather than having to find your phone scan your key then enter a code. Too much of a hassle.

**Comment by PadowYT2** [comment]
It is called passkeys 😉

**Comment by VanillaChan6571** [comment]
> It is called passkeys 😉

Then its already suggested in #272
