### ISSUE TITLE
oAuth Applications don't let you login/signup.

### ISSUE THREAD

**Issue by TheBestPenguinYT** [WemXPro/tracker#297]
### Product

WemX

### Describe the issue

You can't login/signup with the oAuth even when enabled in admin settings.

### Product Version

1.9.0

### Pterodactyl Panel Version

1.11.5

**Comment by VanillaChan6571** [comment]
Not a bug since there no code for it anyways. It just a social link page.

**Comment by GC-spigot** [comment]
Up

**Comment by GIGABAIT93** [comment]
In the next version, authorization using social networks will be available
