### ISSUE TITLE
Fixing price array for webhooks

### ISSUE THREAD

**Issue by SaltyLTS** [WemXPro/tracker#298]
### Product

WemX

### Describe the issue

Can't reach price array for packages webhooks 

### Product Version

1.9.0

### Pterodactyl Panel Version

1.11.5

**Comment by Mubeen142** [comment]
Hi @SaltyLTS 

In the next update, I added the ability to set any property from the order model, you can also pass custom blade syntax and emails now support variables too.

There's a breaking change, the syntax has changed from: `$order->price['price']` to `{{ $order->price['price'] }}` so you need to wrap the variables inside {{ }}

A more detailed documentation guide will follow for this before the update
