### ISSUE TITLE
Fix typo in payment successful 

### ISSUE THREAD

**Issue by SaltyLTS** [WemXPro/tracker#299]
### Product

WemX

### Describe the issue

https://pic.salty.rip/bEda4/CAKIjOwE11.png

It's Successful not Successfully

### Product Version

1.9.0

### Pterodactyl Panel Version

1.11.5

**Comment by Mubeen142** [comment]
thanks for reporting this. "Payment Successfully" has been changed to "Payment Completed" for English next update
