### ISSUE TITLE
Password requirements not required 

### ISSUE THREAD

**Issue by Breugeltje** [WemXPro/tracker#307]
### Product

WemX

### Describe the issue

User's can change there password to anything they like even a single character password like "b" after this when they try to login they get the error: Error! The password must be at least 4 characters.
also the only requirement for the password at signup is 4 characters so "bbbb" is allowed as a password

### Product Version

1.9.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

sign up with a test account en try password "bbbb" and then  in user/settings change the password to "b". now logout en try logging in.

### Expected Behaviour

when signing up or changing password the password requirement should be forced
like below the password changing area is stated:
Ensure that these requirements are met:
At least 10 characters (and up to 100 characters)
At least one lowercase character
Inclusion of at least one special character, e.g., ! @ # ?

I would like to add:
At least one upercase character
At least one numeric character

**Comment by Mubeen142** [comment]
Thank you for reporting this bug, it has been fixed for next update
