### ISSUE TITLE
Brave Shields will break cookies consent

### ISSUE THREAD

**Issue by GeekCornerGH** [WemXPro/tracker#319]
### Describe the issue

Default Brave Shield will break cookies consent feature

### Product Version

1.9.1 probably?

### To Reproduce

1. Use Brave with Brave Shields enabled
2. Go on the demo instance (or any wemx-powered website) on a private navigation, fresh installation or so

### Expected Behaviour

Brave should hide properly the cookies page without disabling shields

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/45696571/ffb6070a-3621-41bd-b342-3a89bd1330d7)
Guest mode

**Comment by thattheredstoner** [comment]
This is more of an issue on Brave's end, you should click on the Brave shield icon, disable the shield and click "Report site", this will notify Brave developers about the issue.

**Comment by SiFuMax09** [comment]
But this Issue first poped up when cookies was introduced.

**Comment by thattheredstoner** [comment]
It's Brave's tracker blocker or cookie pop-up blocker, not sure which one, but most likely the cookie pop-up blocker

**Comment by GeekCornerGH** [comment]
> It's Brave's tracker blocker or cookie pop-up blocker, not sure which one, but most likely the cookie pop-up blocker

Cookie popup tracker

**Comment by Mubeen142** [comment]
This is not an issue with WemX
