### ISSUE TITLE
Can't resolve error in Logs

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#320]
### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/127934270/b7e43270-9d94-4950-b27a-5e9e07e5e92c)

I click in Resolve "Resolver" and nothing happens. 

### Product Version

1.9.1

### To Reproduce

Go to Admin panel, configuration, logs, errors and click on Resolve. 

### Expected Behaviour

Delete the error I think.

**Comment by Mubeen142** [comment]
Hi,

Thanks for reporting this bug. Not all issues in logs can be resolved automatically, I have added code that hides logs that cant be resolved automatically.
