### ISSUE TITLE
Confirmation error

### ISSUE THREAD

**Issue by Coderbot4321** [WemXPro/tracker#321]
### Describe the issue

When  I complete the check out on a server, the screen just buffers and no confirmation shows. It takes 2-3 minutes before the confirmation screen shows. There is no logs on this and the debug mode shows nothing.

### Product Version

1.9.1

### To Reproduce

Click complete checkout, Screen buffers for a while.

### Expected Behaviour

Confirmation message  shows after purchase.

**Comment by Mubeen142** [comment]
@Coderbot4321 

We need more information, the current description provided is quite vague.

I need the following info:

- Service you are using for the package
- Gateway you are using, also check if the error happens with other gateways
- Steps to reproduce
- using custom theme?

A video would also help and the link in the browser where the error occurs.

Feel free to reopen the ticket once you have that information for us
