### ISSUE TITLE
High Prio Bugs - Upgrading and Buying new Servers

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#325]
### Describe the issue

Users can Upgrade to every Type of Server, even unlisted and ADMIN ONLY ones!
<img width="1387" alt="image" src="https://github.com/WemXPro/tracker/assets/60582586/91fb5efb-30f9-4012-9152-21c1793c48ae">
<img width="304" alt="image" src="https://github.com/WemXPro/tracker/assets/60582586/4df53041-446f-4bbe-b881-8134ed3ab04a">

And also is it possible to buy Servers on Full Nodes (Out of Stock) 
<img width="386" alt="image" src="https://github.com/WemXPro/tracker/assets/60582586/886bf6bd-9372-4514-a58d-de597e3dbda8">

### Product Version

1.9.1

### Pterodactyl Panel Version (if applicable)

1.11.5

**Comment by Mubeen142** [comment]
Hey thank you for reporting this.

Luckily this bug didn't have any real impact since we already had a check in place in the backend that checks whether a package was active, if it wasn't it would return an error.

I have also updated the HTML now to hide inactive packages
