### ISSUE TITLE
Upgrade / Downgrade package not working well. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#330]
### Describe the issue

The upgrades and downgrades are broken, they only look at the price difference over time to decide what you pay today. But if you buy a lower package and then upgrade to a higher one, you only pay the difference in days, not the price difference. For example, I bought the basic 2GB for $4.99, then I go to upgrade and select the gold 6GB and pay $1.13, so that month instead of paying $9.99 for the gold, I will have paid $6.12. And then you can keep playing with this as much as you want. Additionally, if you downgrade a package, your balance part (diff or days and price) will not be refunded. I would review it. 

![image](https://github.com/WemXPro/tracker/assets/127934270/6af0ed59-68fc-47d7-8891-14beb29a1f2c)

### Product Version

1.9.4

**Comment by Mubeen142** [comment]
Thank you for reporting this issue.

I have added a new field in the package price settings which allows you to add a "upgrade fee" the user has to pay each time upgrading to a higher plan. You can use this upgrade fee field to define a fee to prevent misuse
