### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by expxx** [WemXPro/tracker#334]
### Describe the solution you'd like

Implement a REST API to control actions of the panel such as adding credit, editing/adding/deleting users, etc

### Describe alternatives you've considered

Somehow authenticate as the user, grab the token, and make requests. Doesn't work like that.

**Comment by Mubeen142** [comment]
Thank you for your suggestion,

We have created a new API for WemX in the next update.

You can view the endpoints here: https://wemx.gitbook.io/wemx-api/api-reference/users
