### ISSUE TITLE
Never sent the welcome and leave emails. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#336]
### Describe the issue

I never received any email from the welcome and leave that are in the messages section inside emails inside the admin panel.

### Product Version

1.9.4

**Comment by SiFuMax09** [comment]
Which email do you used? If it's a gmail or Hotmail or something from big providers it's possible that you don't setuped email security correct

**Comment by PadowYT2** [comment]
This is not a bug, but something is unconfigured
