### ISSUE TITLE
WemX Images for packets messed up

### ISSUE THREAD

**Issue by Pnuky** [WemXPro/tracker#337]
### Describe the issue

There is a problem with images attached to packets.

No matter how many times you are changing the images once this problem occurs the images are being loaded for packets randomly.

### Product Version

1.9.1

### Pterodactyl Panel Version (if applicable)

1.11.5

### To Reproduce

1. Create packet.
2. Fill neccesary fields.
3. Attach image.
4. Check image on servers packets tab
5. Get back to packet options
6. Upload new image
7. Image is missing
8. Check which image is loaded on packed on landing page
9. Images are appearing randomly from other packets.

### Expected Behaviour

Latest image uploaded to packet should appear.

### Screenshots

![obraz](https://github.com/VertisanPRO/tracker/assets/16953449/721786ab-66c6-44da-b274-82c896e544af)

### Additional Information

There is also missing title 
![obraz](https://github.com/VertisanPRO/tracker/assets/16953449/1178ab09-c407-4c30-acd7-4a0a2df0eaa6)

**Comment by GIGABAIT93** [comment]
Hi, I did everything you described and I didn't have any problems. Are you still having this problem?

**Comment by GIGABAIT93** [comment]
in the next update, the icon will be displayed when editing the package
