### ISSUE TITLE
The correct price does not come out big.

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#339]
### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/127934270/5f7d90f6-ba49-4b02-b5fe-8e7cb6f415c3)

It would be necessary to set the lower price to make it bigger, so people see it.

### Product Version

1.9.4

**Comment by VanillaChan6571** [comment]
No the big out is correct as they will pay 2 every month or week. Not a bug
