### ISSUE TITLE
aline the Buttons please

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#340]
### Describe the solution you'd like

Please aline the Buttons on the Bottom, thx
<img width="1262" alt="image" src="https://github.com/WemXPro/tracker/assets/60582586/bf5368ee-ab76-4bf2-93c9-b67c4be6e625">

**Comment by DAMO11-coder** [comment]
you can do that your self in code.

**Comment by Niclas-M1** [comment]
> you can do that your self in code.

ok, ok
do you know where exactly?

**Comment by GIGABAIT93** [comment]
this is already implemented in the latest version
