### ISSUE TITLE
Add the Accept the terms and conditions button on checkout. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#342]
### Describe the solution you'd like

Add the button so users accept the terms.

**Comment by Mr-sl1d3r** [comment]
It already exists as a feature when you create the page for terms and service call it `terms-and-conditions` so it will pop up for you
![image](https://github.com/WemXPro/tracker/assets/76396365/b0718b44-dbd0-4853-8f23-e2a754d26e18)
if there are any problems tell me
