### ISSUE TITLE
Option to set custom prices for a Service, when creating it on the Admin-Dashboard

### ISSUE THREAD

**Issue by Niclas-M1** [WemXPro/tracker#347]
### Describe the solution you'd like

A Option to set custom prices for a Service, when creating it on the Admin-Dashboard, like creating a free Server or so for a Person, or make it a little bit cheaper for the one Person when creating the Server over the Admin Dashboard.

**Comment by VanillaChan6571** [comment]
Already possible when using custom price data like:
{
    "type": "recurring",
    "period": 30,
    "price": 1.42,
    "renewal_price": 1.42,
    "setup_fee": 0,
    "cancellation_fee": 0,
}

**Comment by Niclas-M1** [comment]
Oh, ok nice thx.
