### ISSUE TITLE
Add PayPal express checkout. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#348]
### Describe the solution you'd like

Paypal express checkout is more secure and gives some advantages than the normal checkout.

**Comment by VanillaChan6571** [comment]
Already Exists

**Comment by GIGABAIT93** [comment]
![зображення](https://github.com/WemXPro/tracker/assets/59637348/09ffb441-325a-4496-8db2-bd08a0c690e6)
PayPal itself does not recommend using it and this method is not supported. I don't think it will be added

**Comment by joti-prime** [comment]
There is a method like PayPal subscription but not for subscriptions that uses also the clientid and secret. I’m referring to that method (is similar to express checkout but is not deprecated)
