### ISSUE TITLE
Pterodactyl - Restart server option in checkout

### ISSUE THREAD

**Issue by LeanoJ** [WemXPro/tracker#350]
### Describe the solution you'd like

I have the idea that it might be possible to include the option in the checkout that the buyer can set up a defined restart of the purchased server. this might then lead to fewer problems for the customer and fewer support cases. 

My idea would be to create a checkbox with restart.
If this is clicked, then a time can be defined via drop down (minutes, seconds) then a task schedule is created that runs daily at the time specified by the customer.

**Comment by GIGABAIT93** [comment]
I don't quite understand what you mean. If there is a pterodactyl panel about restarting the server, then there is already a scheduler for this
