### ISSUE TITLE
Subpages & Subpages Sidebar

### ISSUE THREAD

**Issue by LeanoJ** [WemXPro/tracker#353]
### Describe the solution you'd like

Feature 1: Subpage Creation

Currently, our software organizes pages directly under the main domain, such as https://example.com/p/page. However, it would be highly beneficial to implement a feature that enables the creation of subpages under existing pages. This would allow for URLs like https://example.com/p/page/subpage, creating a hierarchical structure.

The introduction of subpages would simplify content organization and navigation for our users, making it more intuitive and user-friendly.

Feature 2: Subpage Sidebar

In addition to subpage creation, we propose implementing a sidebar option that displays a list of subpages when viewing a parent page. For example, when users navigate to https://example.com/p/page, a sidebar could list related subpages, such as "Palworld," "Minecraft," and others.

This sidebar would enhance the user experience by providing easy access to associated subpages, improving navigation within our software.

**Comment by GIGABAIT93** [comment]
A module was developed that implements this functionality. https://wemx.net/resources/show/43
