### ISSUE TITLE
Ticket does not change page automatically

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#355]
### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/127934270/555d62b4-aef1-4e9a-8459-aad78be4c04d)

If the last message is on page 2, when the ticket is opened, it should show page two and not page 1. There are people who do not realize that and it is annoying to always have to change to the last one.

### Product Version

1.9.1

**Comment by Mubeen142** [comment]
Tickets will now be displayed from latest messages to oldest which should also fix this issue
