### ISSUE TITLE
Billing Buffer

### ISSUE THREAD

**Issue by Coderbot4321** [WemXPro/tracker#357]
### Describe the issue

Hello there, I have been having this issue come up and cant fix it. Whenever a customer pays wither with balance, card, etc. The web page just buffers for a bit and some customers have accidently clicked the Buy button again and it will charge twice. I was think you could have it redirect to a loading page or something. Any idea on how to fix?

### Product Version

1.9.1

### Pterodactyl Panel Version (if applicable)

NA

### To Reproduce

Go to purchase a server, Click the final button. Wait

### Expected Behaviour

Click the button, Payment is confirmed.

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
