### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Coderbot4321** [WemXPro/tracker#361]
### Describe the issue

I updated to Wemx v2 and no of the features are active. I think that something went wrong on the install.
I would try to reinstall but I cant change the Authorized IP and I get the you arent authorized to access this when I try.

### Product Version

2.0.0

### Pterodactyl Panel Version (if applicable)

NA

### To Reproduce

Update to Wemx 2.0.0

### Expected Behaviour

Update is applyed.

### Additional Information

I have already rebooted my machine.

**Comment by Mubeen142** [comment]
Hi, this is not a bug report.

Please contact us on discord for support
