### ISSUE TITLE
Chnage Admins perms/groups 

### ISSUE THREAD

**Issue by EWANZO101** [WemXPro/tracker#363]
### Describe the solution you'd like

 could we explore the possibility of enhancing permissions? Perhaps allowing administrators to customize access for support staff by specifying the areas, services, or modules they can access. For instance, imagine having a dedicated Petro Panel team that can exclusively view clients, areas, and related elements within the Petro Panel

**Comment by PadowYT2** [comment]
This is a tracker for WemX, not Pterodactyl
