### ISSUE TITLE
Add back the contact us form. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#366]
### Describe the solution you'd like

You say that it is replaced by the ticket system, but no, contact us allows you to contact without having an account, tickets do not.

### Describe alternatives you've considered

Add it again.

**Comment by Ariz-z** [comment]
Yes I agree with you add the contact us page again not everyone will create account for making tickets for a simple question and also not everyone have discord account if you tell discord exist for support 🙂

**Comment by VanillaChan6571** [comment]
No.

**Comment by VanillaChan6571** [comment]
WemX 2.0.0 Removed "Contact Us", use the Tickets Module instead.

If you know how to edit php, then you can manually add it yourself.
