### ISSUE TITLE
Check box Terms in checkout validation not working.

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#370]
### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/127934270/4b343bfe-e87f-4c6f-9d86-f259de08c464)

missing validation / not working the check of accepting terms. People can complete the order without checking the box.

### Product Version

2.0.0

### Expected Behaviour

If you don’t check the box an error

**Comment by Mubeen142** [comment]
Thanks for reporting, this will be fixed in the next version (2.0.1)

**Comment by Ariz-z** [comment]
I also try but this is still not working

**Comment by SiFuMax09** [comment]
Are you using a custom theme?

**Comment by Mr-sl1d3r** [comment]
> Are you using a custom theme?

Yes I use a customised theme the check box stops working. Whereas using the default theme works

**Comment by VanillaChan6571** [comment]
Then this should be closed since you copied the template from an older wemx version that **did not have this fix/new feature.**
