### ISSUE TITLE
Visual bugs with emails.

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#371]
### Describe the issue

1 the comma that appears. 2 the color of the font in the email history. 3 the /n (in some places there are /n is some other no. Also I don’t know why we want three /n between the text and the details of the product.

You have a video on my discord ticket, I don't want to show my details here. 

### Product Version

2.0.0

**Comment by Mubeen142** [comment]
Thanks for reporting, this will be fixed in the next version (2.0.1)
