### ISSUE TITLE
Module update

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#376]
### Describe the issue

![image](https://github.com/WemXPro/tracker/assets/127934270/2c2bcc14-61ec-465e-bf0e-c49bc8e64904)

It says me update even the ticket module is updated, don't know if is ticket module error or wemx. 

### Product Version

2.0.1

**Comment by SiFuMax09** [comment]
It also installs the first release and not the newest

**Comment by VanillaChan6571** [comment]
You can install the newest manually.

**Comment by GIGABAIT93** [comment]
The problem is that the current version is not specified in the configuration module. That's why it keeps asking you to update it, but when you click update it will install the latest version
