### ISSUE TITLE
Add an option to automatically delete the terminated orders. 

### ISSUE THREAD

**Issue by joti-prime** [WemXPro/tracker#380]
### Describe the solution you'd like

Add that option so you can enable it and set the time you want to wait until is deleted.

**Comment by GIGABAIT93** [comment]
I don't think it's a good idea because deleting orders will lead to incorrect display of statistics since orders are closely related to payments

**Comment by joti-prime** [comment]
Hello, If you have a user limit, this limit also includes terminated orders, so or you automatically delete these ones or exclude user limit in the terminated orders please.

**Comment by GIGABAIT93** [comment]
Hi ok will be added in the next update
