### ISSUE TITLE
Repair "Default Language" feature

### ISSUE THREAD

**Issue by MyMQL** [WemXPro/tracker#381]
### Describe the solution you'd like

The "default language" option in the admin area doesnt work, the system just ignores it and every new user have the english as the default language. So please repair that and make sure that when i set a language to be default for the panel, then all of the new users will start with that language, not english.

### Additional context

(Mubeen asked me to publish that idea on github when i made a message about it on discord)

**Comment by VanillaChan6571** [comment]
If you want to set the default language for new users you can edit file 

app/Http/Controllers/Auth/AuthController.php

Add new line at line 137
$user->language = “en”;

**Comment by MyMQL** [comment]
> If you want to set the default language for new users you can edit file
> 
> app/Http/Controllers/Auth/AuthController.php
> 
> Add new line at line 137 $user->language = “en”;

Yes, but that only works for users that have created a account and only if there are signed in, and i should work even for people that are not logged in to the panel.

**Comment by GIGABAIT93** [comment]
For the guest, the language is determined automatically, if the desired language is not found, then the default language is set, which can be configured in the file config/app.php 
![зображення](https://github.com/WemXPro/tracker/assets/59637348/e35cbb4b-1619-4cd0-96c5-729bee1dfc2e)
