### ISSUE TITLE
Addition of gift cards to buy

### ISSUE THREAD

**Issue by Mr-sl1d3r** [WemXPro/tracker#382]
### Describe the solution you'd like

It would be nice to have the possibility to put a category for gift cards, a user buys this gift card and is generated a code with a duration that can be chosen from the administration panel usually 1 or 2 years. The user can choose whether to email the giftcard or not

### Describe alternatives you've considered

maybe put gifcards with set prices such as 10, 20, 50 100 etc. add the possibility of being able to insert a personalised message if the user decides to email it to the user who wants to send it and to redeem the code there is a button and it is added to the account balance of the user who redeems it

**Comment by Princelion33** [comment]
It would be good

**Comment by SiFuMax09** [comment]
Yeah Module is in development

**Comment by SiFuMax09** [comment]
The Module is finished and get his final toutches and it will be puplished later this day!
