### ISSUE TITLE
Possibility of including a sub-domain of one's choice

### ISSUE THREAD

**Issue by Mr-sl1d3r** [WemXPro/tracker#383]
### Describe the solution you'd like

it would be nice to be able to let the user choose during payment whether to include a sub-domain, perhaps with the possibility of being able to choose whether to charge e.g. €0.15 or €1

### Describe alternatives you've considered

with this to also refer to the cloudflare api so as to make domain creation automatic this could be useful for minecraft for example

**Comment by GIGABAIT93** [comment]
I am working on a separate service that will allow selling subdomains separately and will have integration with pterodactyl where the user in the server settings will be able to set a subdomain for the server if you allow it for his package. It will not be integrated directly into the pterodactyl service, and when purchasing a package, the user will not be able to select a subdomain, but only after purchase in the settings
