### ISSUE TITLE
Missing things in API documentation

### ISSUE THREAD

**Issue by Partymann2000** [WemXPro/tracker#384]
### Describe the issue

https://wemx.gitbook.io/wemx-api/api-reference/categories
https://wemx.gitbook.io/wemx-api/api-reference/packages
https://wemx.gitbook.io/wemx-api/api-reference/emails
![image](https://github.com/WemXPro/tracker/assets/53320411/f6fbcb47-f8b2-44f1-aa16-75a2405f3250)
on this 3 sections are missing a / after the v1

### Product Version

2.0.1

**Comment by Mubeen142** [comment]
thank you for reporting this, it has been fixed
