### ISSUE TITLE
Labels 

### ISSUE THREAD

**Issue by amomagus** [WemXPro/tracker#393]
### Describe the solution you'd like

Would be nice if you could assign labels to products like: popular

**Comment by PadowYT2** [comment]
Duplicate of #132

**Comment by Mr-sl1d3r** [comment]
I solved the problem by doing an implementation in my portal code so I get
![image](https://github.com/WemXPro/tracker/assets/76396365/aa5267a4-b6c8-4895-961f-5d93a33969a9)
