### ISSUE TITLE
Unable to scroll down to click Accept All (to cookies)

### ISSUE THREAD

**Issue by HunterShenep** [WemXPro/tracker#394]
### Describe the issue

Hello, wanted to give you guys a headsup that my "iPhone SE" is unable to scroll down far enough to click the Accept Cookies button. Technically I can scroll down there, but I can't click the button with my other finger - it just resets the scroll bar back up.
Here's a demonstration
[](https://huntershenep.com/wemx-issue.mp4)
https://huntershenep.com/wemx-issue.mp4

### Product Version

1.4.0

### Pterodactyl Panel Version (if applicable)

1.4.0

### To Reproduce

Visit a homepage of wemx with an iPhone SE

### Expected Behaviour

To be able to accept or deny cookies

### Screenshots

Attached a URL to a video above.

### Additional Information

a

**Comment by VanillaChan6571** [comment]
Mobile Phones are afterthought when making websites. No real methods to really support a screen size of 144p resolution.
