### ISSUE TITLE
Add color palette settings for icons in the Unix side menu

### ISSUE THREAD

**Issue by infnibor** [WemXPro/tracker#396]
### Describe the solution you'd like

I have a suggestion for the next version of Unix - add the ability to set different icon colors in the side menu of both different modes. 

### Describe alternatives you've considered

This means that there should be 1 color palette to define for the dark mode, and 2 palettes for the light mode.

### Additional context

![image](https://github.com/WemXPro/tracker/assets/156368035/110802a1-7ac2-48e4-a489-897428cf6017)
![image](https://github.com/WemXPro/tracker/assets/156368035/8c3db545-1548-4dd2-bbf6-2fd08550f92a)

**Comment by PadowYT2** [comment]
This is the wrong repository for Pterodactyl products
