### ISSUE TITLE
Ticking "Show Author" off doesn't hide author in articles

### ISSUE THREAD

**Issue by HunterShenep** [WemXPro/tracker#399]
### Describe the issue

Ticking "Show Author" off doesn't hide author in articles

### Product Version

1.4.0

### Pterodactyl Panel Version (if applicable)

1.4.0

### To Reproduce

Admin > Articles

### Expected Behaviour

Not show authors

**Comment by PadowYT2** [comment]
WemX 1.4.0 is really old and not supported
