### ISSUE TITLE
Ticking "Show Author" off doesn't hide author in articles

### ISSUE THREAD

**Issue by HunterShenep** [WemXPro/tracker#400]
### Describe the issue

Ticking "Show Author" off doesn't hide author in articles

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

2.0.1

### To Reproduce

1. Admin
2. Articles
3. Open existing or create new Article
4. Show Author in off position doesn't do anything

**Comment by VanillaChan6571** [comment]
Cannot Reproduce This Issue. You might have a broken client theme or non-updated client theme. (Would Close This but not a Github Mod)

**Comment by GIGABAIT93** [comment]
Will be fixed in the next update
