### ISSUE TITLE
Node Location

### ISSUE THREAD

**Issue by AlfanGA** [WemXPro/tracker#401]
### Describe the issue

I get a node full error for my Premium Node location. Indeed, the first node in the Premium Node category is full, but there is still plenty of storage for other nodes in that category

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

2.0.1

### Screenshots

![Screenshot 2024-02-25 165827](https://github.com/WemXPro/tracker/assets/90809610/2dec8214-b04f-47c0-b082-f6600bb72b0c)
![Screenshot 2024-02-25 165850](https://github.com/WemXPro/tracker/assets/90809610/87b463d9-3cbe-416c-9b31-c4079b426468)

**Comment by EWANZO101** [comment]
![Screenshot 2024-03-02 120341](https://github.com/WemXPro/tracker/assets/107235474/00c58012-7549-4b72-85c7-4ac1a054fb1b)
DID U ADD THEM ALL ON THE PACKAGES HERE AND ALSO ARE THEY FULLY ONLINE ?

**Comment by EWANZO101** [comment]
ALso check here 
![Uploading jjjjjjjjjjjjjjjjjjjjjjjjj.png…]()

**Comment by NOXITB** [comment]
The fk why is their like 976tb of ram 
<img width="782" alt="Screenshot 2024-03-02 at 10 32 01 pm" src="https://github.com/WemXPro/tracker/assets/77712352/9b7e899c-b7e8-4db3-881a-6846c3196b1c">

**Comment by AlfanGA** [comment]
> ALSO CHECK HERE ![jjjjjjjjjjjjjjjjjjjjjjjjj](https://private-user-images.githubusercontent.com/107235474/309471862-d521bb01-316b-4dd3-a73e-991570015347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODU2MDIsIm5iZiI6MTcwOTM4NTMwMiwicGF0aCI6Ii8xMDcyMzU0NzQvMzA5NDcxODYyLWQ1MjFiYjAxLTMxNmItNGRkMy1hNzNlLTk5MTU3MDAxNTM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMzE1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzNmMTZmZTBmYWRmODkxZTljOGY2MjBmOGY4ZmFkYmUxMWU2MjM5N2M5NmJmY2M0ZTY2ZjkxZGQ5Y2RkZDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7aCW6AobdFaeuju5YQtsCLgQC4hi4BqVIdKuvjNfrk4)

the issue its already fixed by updating the pterodactyl module , thank you

**Comment by AlfanGA** [comment]
the issue its already fixed by updating the pterodactyl module , thank you
