### ISSUE TITLE
Deletion of all user's orders when the user is blocked

### ISSUE THREAD

**Issue by IkdanYT** [WemXPro/tracker#402]
### Describe the solution you'd like

When a user is locked out, their orders should be deleted/frozen, should be configurable in settings or any other section. At least deletion/forced deletion/freezing of pterodactyl and hestia servers.

Переведено с помощью DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by Mubeen142** [comment]
Thank you for your suggestion, this was added and will be available in the next update.
