### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by sybetjeh** [WemXPro/tracker#406]
### Describe the issue

The reset password button seems to be funky

### Product Version

2.0.1

### Expected Behaviour

Button should be normal

### Screenshots

https://cdn.discordapp.com/attachments/1129104624033468466/1213147850897236099/5pxWfYb.png?ex=65f46afa&is=65e1f5fa&hm=41de5494c2b77147243479d12fab72ea30dad3374c74a7e1b17db2ebb5203726&

**Comment by VanillaChan6571** [comment]
Known Issue, You can edit/manually change the email template.

**Comment by sybetjeh** [comment]
where?
in the admin panel you can only edit a part of it, not the full template

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
