### ISSUE TITLE
Renew suspended order not working

### ISSUE THREAD

**Issue by llyrdavies** [WemXPro/tracker#408]
### Describe the issue

I've attached a screenshot, the yellow renew button does nothing. Users are required to renew using the green button.

### Product Version

2.0.1

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/146123002/42642f0b-6d42-47b9-b700-c6699e3ae77a)

**Comment by VanillaChan6571** [comment]
Known, the Green Renew buttons works though.

**Comment by Mubeen142** [comment]
Thank you for reporting this, ive removed the yellow renew button as there is already one on the screen
