### ISSUE TITLE
Resend Verification Email

### ISSUE THREAD

**Issue by VortexxJS** [WemXPro/tracker#411]
### Describe the solution you'd like

A simple text / button that gives you the chance to resend the verification email (every 60 seconds to avoid spam maybe).

**Comment by PadowYT2** [comment]
Already exists within Admin > Customers > Emails

**Comment by VortexxJS** [comment]
Thats not what i mean, this is only accessible to admins, but not to the users themselves. I dont think i would want to have a user to ask me everytime they need to resend their verification code..

**Comment by PadowYT2** [comment]
Duplicate of WemXPro/tracker#345
