### ISSUE TITLE
order upgrade

### ISSUE THREAD

**Issue by pirojok95** [WemXPro/tracker#413]
### Describe the issue

When you upgrade the order everything goes through without problems, but RAM and so on are not updated

### Product Version

2.2.1

### Pterodactyl Panel Version (if applicable)

1.11.5

**Comment by SiFuMax09** [comment]
Mubeen the pterodactyl service is a private repo and only you can access it. I think he means ptrodactyl but Who knows.

**Comment by EWANZO101** [comment]
> Mubeen the pterodactyl service is a private repo and only you can access it. I think he means ptrodactyl but Who knows.

try this https://github.com/EWANZO101/WF/blob/fde3bd3936bda4b0620512a93f8d4c0e47357f3d/services.php#L277
