### ISSUE TITLE
Making a Pterodactyl theme for WemX Pro

### ISSUE THREAD

**Issue by PadowYT2** [WemXPro/tracker#96]
### Resource

WemX Pro

### Describe the solution you'd like

Make a Pterodactyl theme that would look like WemX Pro and would have a lot of features

**Comment by VanillaChan6571** [comment]
Is this still going to be opened? I thought this was abandoned?

**Comment by PadowYT2** [comment]
> Is this still going to be opened? I thought this was abandoned?

Yes, of course

**Comment by PadowYT2** [comment]
> Is this still going to be opened? I thought this was abandoned?

Yes, of course
